# -*- coding: utf-8 -*-
"""Hyper-Local Market Trend Analysis (India/Odisha Specific).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL6fJQbIlS4zwZVgmF5emH3B_gRqu9Em
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('Agriculture_price_Mandi_dataset.csv')

"""**Data Cleaning of Agriculture_price_Mandi_dataset**"""

df

df.shape

df.info()

df.describe()

df.isnull().sum()

df[df.duplicated()]

for col in df.columns:
  if df[col].nunique() < 100:
    print(df[col].value_counts())
    print("-"*50)

df['STATE'].replace({'Chhattisgarh':'Chattisgarh','Jammu and Kashmir':'Jammu & Kashmir'},inplace=True)

df['STATE'] = df['STATE'].str.strip()

for col in df.columns:
  if df[col].nunique() < 100:
    print(df[col].value_counts())
    print("-"*50)

for col in df.columns:
    count = (df[col].astype(str) != df[col].astype(str).str.strip()).sum()
    if count > 0:
        print(col, "->", count)   # check columns space is available or not

df['Price Date'] = pd.to_datetime(df['Price Date'])

df.info()

numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
print(f"Numerical columns identified for outlier detection: {numerical_cols}")

cols = ['Min_Price', 'Max_Price', 'Modal_Price']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(2, 2, i) # Changed subplot layout to 2 rows, 2 columns
    sns.boxplot(y=df[col], color='skyblue', width=0.3)
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

from scipy import stats

import numpy as np
z_scores = np.abs(stats.zscore(df[['Min_Price', 'Max_Price', 'Modal_Price']]))

df_clean = df[~(z_scores > 3).any(axis=1)]

cols = ['Min_Price', 'Max_Price', 'Modal_Price']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(2, 2, i) # Changed subplot layout to 2 rows, 2 columns
    sns.boxplot(y=df_clean[col], color='skyblue', width=0.3)
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""**Data Cleaning of Rice Vegitable price Prediction**"""

df1=pd.read_csv('Rice_vegetable_Price_Prediction.csv')

df1

df1.shape

df1.info()

df1.describe()

df1.isnull().sum()

df1.isnull().sum()/df1.shape[0]*100

df1[df1.duplicated()]

for col in df1.columns:
  if df1[col].nunique() < 50:
    print(df1[col].value_counts())
    print("-"*50)

df1 = df1.dropna(subset=['admin1', 'admin2', 'latitude', 'longitude'])

df1.isnull().sum()

df1.shape

for col in df1.columns:
    count = (df1[col].astype(str) != df1[col].astype(str).str.strip()).sum()
    if count > 0:
        print(col, "->", count)   # check columns space is available or not

df1.dtypes

df1['date']=pd.to_datetime(df1['date'])

df1.dtypes

df1.columns = [col.title() for col in df1.columns]

df1.columns

numerical_cols = df1.select_dtypes(include=np.number).columns.tolist()
print(f"Numerical columns identified for outlier detection: {numerical_cols}")

cols = ['Market_Id', 'Latitude', 'Longitude', 'Commodity_Id', 'Price', 'Usdprice']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(3, 2, i) # Changed subplot layout to 3 rows, 2 columns to accommodate 6 plots
    sns.boxplot(y=df1[col], color='skyblue', width=0.3) # Changed df to df1
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

from scipy import stats

import numpy as np
z_scores = np.abs(stats.zscore(df1[['Commodity_Id', 'Price', 'Usdprice']]))

df1_clean = df1[~(z_scores > 3).any(axis=1)]

cols = ['Commodity_Id', 'Price', 'Usdprice']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(2, 2, i) # Changed subplot layout to 2 rows, 2 columns
    sns.boxplot(y=df1_clean[col], color='skyblue', width=0.3) # Changed df_clean to df1_clean
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()